from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import desc
from core.database import get_db
from models.domain import LearnerProfile, User

router = APIRouter(prefix="/api/gamification", tags=["Affective Engine"])

@router.get("/profile")
def get_learner_profile(user_id: str, db: Session = Depends(get_db)):
    """US-005: Fetches learner XP, level, and streak_days"""
    profile = db.query(LearnerProfile).filter(LearnerProfile.user_id == user_id).first()
    if not profile:
        raise HTTPException(status_code=404, detail="Profile not found")
    
    return {
        "xp_total": profile.xp_total,
        "current_level": profile.current_level,
        "streak_days": profile.streak_days,
        "player_type": profile.player_type.value,
        "engagement_score": profile.engagement_score
    }

@router.get("/leaderboard")
def get_leaderboard(scope: str = "global", player_type: str = None, db: Session = Depends(get_db)):
    """US-004 & PRD 4.2.2: Contextual leaderboard"""
    query = db.query(User.email, LearnerProfile.xp_total, LearnerProfile.player_type).join(LearnerProfile)
    
    if scope == "private" and player_type:
        query = query.filter(LearnerProfile.player_type == player_type)
        
    leaders = query.order_by(desc(LearnerProfile.xp_total)).limit(10).all()
    
    return {"entries": [{"username": l.email.split('@')[0], "xp": l.xp_total, "type": l.player_type.value} for l in leaders]}

@router.get("/quests")
def get_active_quests():
    """PRD 4.2.2: Adaptive solo/team challenge missions (Mock payload for MVP)"""
    return [
        {"id": 1, "type": "solo", "title": "Debug the System", "reward_xp": 50, "status": "active"},
        {"id": 2, "type": "team", "title": "Algorithm Relay", "reward_xp": 150, "status": "locked"}
    ]

@router.get("/notifications")
def get_notifications():
    """Fetches recent mechanic triggers generated by Affective Engine"""
    return [
        {"id": 1, "type": "achievement", "message": "You leveled up!", "read": False},
        {"id": 2, "type": "ai_adapted", "message": "Path simplified based on recent performance.", "read": True}
    ]